#!/usr/bin/env python3
"""Generate offline person proxy masks for G0-2A diagnostics.

These masks are generated by Ultralytics post-processing and are not
bit-identical to DT-SLAM's C++ YOLOSegment output. They are diagnostic proxy
labels, not motion ground truth and not semantic-baseline replacements.
"""

import argparse
import csv
from pathlib import Path

import cv2
import numpy as np
from ultralytics import YOLO


def load_rgb_paths(sequence_root: Path, association_file: Path):
    paths = []
    with association_file.open("r", encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, start=1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            fields = stripped.split()
            if len(fields) < 4:
                raise ValueError(
                    f"Malformed association line {line_number}: {stripped}"
                )
            rgb_path = sequence_root / fields[1]
            if not rgb_path.is_file():
                raise FileNotFoundError(rgb_path)
            paths.append(rgb_path)
    if not paths:
        raise ValueError("Association file contains no RGB-D pairs")
    return paths


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("model", type=Path)
    parser.add_argument("sequence_root", type=Path)
    parser.add_argument("association_file", type=Path)
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--confidence", type=float, default=0.5)
    parser.add_argument("--iou", type=float, default=0.45)
    parser.add_argument("--image-size", type=int, default=640)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args()
    if args.overwrite and args.resume:
        raise ValueError("--overwrite and --resume are mutually exclusive")

    rgb_paths = load_rgb_paths(args.sequence_root, args.association_file)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = args.output_dir / "manifest.csv"
    if manifest_path.exists() and not (args.overwrite or args.resume):
        raise FileExistsError(
            f"{manifest_path} exists; pass --overwrite or --resume"
        )

    model = YOLO(str(args.model), task="segment")
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))
    records = []
    for index, rgb_path in enumerate(rgb_paths):
        filename = f"frame_{index:06d}.png"
        output_path = args.output_dir / filename
        if output_path.exists() and args.resume:
            proxy_mask = cv2.imread(str(output_path), cv2.IMREAD_GRAYSCALE)
            if proxy_mask is None:
                raise RuntimeError(f"Failed to read existing {output_path}")
            records.append(
                {
                    "frame": index,
                    "rgb": str(rgb_path),
                    "mask": filename,
                    "person_instances": -1,
                    "proxy_pixels": int(np.count_nonzero(proxy_mask)),
                }
            )
            continue

        result = model.predict(
            source=str(rgb_path),
            device=args.device,
            imgsz=args.image_size,
            conf=args.confidence,
            iou=args.iou,
            classes=[0],
            retina_masks=True,
            verbose=False,
        )[0]
        height, width = result.orig_shape
        proxy_mask = np.zeros((height, width), dtype=np.uint8)
        instance_count = 0
        if result.masks is not None:
            instance_masks = result.masks.data.cpu().numpy()
            instance_count = int(instance_masks.shape[0])
            if instance_count:
                proxy_mask[np.any(instance_masks > 0.5, axis=0)] = 255
        proxy_mask = cv2.dilate(proxy_mask, kernel)

        if output_path.exists() and not args.overwrite:
            raise FileExistsError(
                f"{output_path} exists; pass --overwrite or --resume"
            )
        if not cv2.imwrite(str(output_path), proxy_mask):
            raise RuntimeError(f"Failed to write {output_path}")
        records.append(
            {
                "frame": index,
                "rgb": str(rgb_path),
                "mask": filename,
                "person_instances": instance_count,
                "proxy_pixels": int(np.count_nonzero(proxy_mask)),
            }
        )
        if index == 0 or (index + 1) % 50 == 0:
            print(
                f"[Semantic Proxy] generated {index + 1}/{len(rgb_paths)}",
                flush=True,
            )

    with manifest_path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=records[0].keys())
        writer.writeheader()
        writer.writerows(records)
    print(f"[Semantic Proxy] saved {len(records)} masks to {args.output_dir}")


if __name__ == "__main__":
    main()
